# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-02 01:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='County ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'َشهرستان',
                'verbose_name_plural': 'شهرستان ها',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=8, verbose_name='Contract Code')),
                ('contract_type', models.PositiveSmallIntegerField(choices=[(1, 'مبایعه نامه'), (2, 'وکالت')], verbose_name='Contract Code')),
                ('property_type', models.PositiveSmallIntegerField(choices=[(1, 'آپارتمان'), (2, 'زمین')], verbose_name='Contract Code')),
                ('region', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('landuse', models.PositiveSmallIntegerField(choices=[(1, 'آپارتمان'), (2, 'زمین')])),
                ('area', models.FloatField()),
                ('percentage', models.FloatField()),
                ('price', models.FloatField()),
                ('price_per', models.FloatField(verbose_name='Price per square meter')),
                ('building_age', models.SmallIntegerField(verbose_name='Building Age')),
                ('structure_type', models.SmallIntegerField(choices=[(0, 'بدون اسکلت'), (1, 'بتونی'), (2, 'فلزی'), (3, 'بتونی و فلزی'), (4, 'بتونی و فلزی'), (4, 'آجر یا بلوک سیمانی')], verbose_name='Structure Type')),
                ('recorded_date', models.DateField()),
                ('postal_code', models.CharField(max_length=6, verbose_name='The first six digits of the zip code')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, srid=4326)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.County')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Province ID')),
                ('name', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان ها',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Province'),
        ),
    ]
