# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 23:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32639, verbose_name='محدوده جغرافیایی'),
        ),
    ]
