# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20181204_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='', max_length=5, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
