# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 02:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20181204_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت جغرافیایی'),
        ),
    ]
