# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20181204_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
