# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20181204_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
    ]
