# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-06 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20181206_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['-county'], 'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
    ]
